version: '3.3'
services:
  gitlab:
    build:
      context: .
      dockerfile: gitlab-ce.dockerfile
    image: gitlab-ce-pi:latest
    container_name: gitlab-ce-pi
    restart: always
    privileged: true
    shm_size: '4gb'

    ports:
      - '5080:80'
      - '5443:443'
      - '5022:22'
      - '5587:587'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
